### ISSUE TITLE
FishMap throwing error for some species & family search results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/expert#6]
User support ticket https://support.ehelp.edu.au/helpdesk/tickets/14160

Some search results are throwing an error page, e.g.https://fish.ala.org.au/taxon/view?key=6dcb8551acdd019cc37ed8de7bd369a4

with stacktrace saying:

    org.grails.web.json.JSONException: JSONArray[0] not found.
	at org.grails.web.json.JSONArray.get(JSONArray.java:172)
	at java_util_List$get$3.call(Unknown Source)
	at au.org.ala.expert.BieService.betterBulkLookup(BieService.groovy:157)
	at au.org.ala.expert.BieService$betterBulkLookup$2.callCurrent(Unknown Source)
	at au.org.ala.expert.BieService.injectGenusMetadata(BieService.groovy:195)
	at au.org.ala.expert.BieService$injectGenusMetadata$3.call(Unknown Source)
	at au.org.ala.expert.TaxonController.view(TaxonController.groovy:68)

Offending code seems to be: https://github.com/AtlasOfLivingAustralia/expert/blob/4e13ae0e18d6c6110f3e6a5e34fb1b020478e339/grails-app/services/au/org/ala/expert/BieService.groovy#L156

and I think the issue is the JSONObject is not respecting normal null checks (see this [SO Q](https://stackoverflow.com/questions/36206176/json-null-data-behaving-strangely)). 

Possible fix is to change to something like:

    if (!JSONObject.NULL.equals(data?.searchDTOList) && data.searchDTOList.size() > i) {

**Comment by nickdos** [comment]
Another error reported ([see ticket](https://support.ehelp.edu.au/helpdesk/tickets/15849)):

https://fish.ala.org.au/taxon/species?key=8c450e60d4c9be9f4fd516db09cc54d3

**Comment by patkyn** [comment]
A search in fishmap calls spatial service with this query http://spatial.ala.org.au/ws/distributions?dataResourceUid=dr803&family=SYNGNATHIDAE. The result of the spatial service returns old LSIDs for the genus, for eg: urn:lsid:biodiversity.org.au:afd.taxon:e7437fab-11f6-4dc1-b8c5-bbe4d616c96a. When BIE bulk lookup is called passing this old LSIDs, it returns an empty list, whereelse, single call to BIE will return the the genus with the new LSID.

**Comment by nickdos** [comment]
Fixed
