### ISSUE TITLE
Hide stacktrace details on error page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/expert#8]
User sees this when an error occurs:

![image](https://user-images.githubusercontent.com/532845/38651524-13688cc6-3e45-11e8-828c-f607575d377c.png)

- [ ] Fix/create `error.gsp` so header/footer are displayed
- [ ] Only show a simple error message with link to support@ala.org.au
- [ ] Hide stacktrace in toggle hide/show div (default hide)
- [ ] Also apply to 404 page (use Grails default pattern)

**Comment by patkyn** [comment]
This has been fixed
